export const WORD_BANK = {
    science_starter: {
        difficulty_level: 1,
        description: "Intro science terms & lab language.",
        color: "orange",
        words: [
            { id: "sci_001", word: "NUCLEUS", length: 7, clue: "The center of an atom containing protons and neutrons" },
            { id: "sci_002", word: "ATOM", length: 4, clue: "Smallest unit of a chemical element" },
            { id: "sci_003", word: "CELL", length: 4, clue: "The basic building block of all living things" },
            { id: "sci_004", word: "GAS", length: 3, clue: "State of matter with no fixed shape or volume" },
            { id: "sci_005", word: "ROOT", length: 4, clue: "Part of a plant that absorbs water from soil" },
            { id: "sci_006", word: "LAVA", length: 4, clue: "Hot liquid rock that erupts from a volcano" },
            { id: "sci_007", word: "ACID", length: 4, clue: "A chemical substance with a pH less than 7" },
            { id: "sci_008", word: "ORBIT", length: 5, clue: "The curved path of a planet around a star" },
            { id: "sci_009", word: "FOSSIL", length: 6, clue: "Preserved remains of an ancient animal or plant" },
            { id: "sci_010", word: "HEAT", length: 4, clue: "Energy transfer due to temperature difference" },
            { id: "sci_011", word: "MASS", length: 4, clue: "A measure of the amount of matter in an object" },
            { id: "sci_012", word: "LENS", length: 4, clue: "Transparent material that focuses light" },
            { id: "sci_013", word: "WAVE", length: 4, clue: "Disturbance that transfers energy apart from matter" },
            { id: "sci_014", word: "MOON", length: 4, clue: "Natural satellite orbiting a planet" },
            { id: "sci_015", word: "IRON", length: 4, clue: "Strong magnetic metal element" },
            { id: "sci_016", word: "BASE", length: 4, clue: "Substance with pH greater than 7" },
            { id: "sci_017", word: "BONE", length: 4, clue: "Rigid organ that constitutes part of the skeleton" },
            { id: "sci_018", word: "SEED", length: 4, clue: "Embryonic plant enclosed in a protective outer covering" },
            { id: "sci_019", word: "LEAF", length: 4, clue: "Green flattened structure of a plant" },
            { id: "sci_020", word: "STAR", length: 4, clue: "Luminous ball of gas, mostly hydrogen and helium" },
            { id: "sci_021", word: "MARS", length: 4, clue: "The Red Planet" },
            { id: "sci_022", word: "SOIL", length: 4, clue: "Upper layer of earth in which plants grow" },
            { id: "sci_023", word: "EGG", length: 3, clue: "Organic vessel allowing embryo development" },
            { id: "sci_024", word: "ION", length: 3, clue: "Atom or molecule with a net electric charge" },
            { id: "sci_025", word: "DNA", length: 3, clue: "Carrier of genetic information" },
            { id: "sci_026", word: "ICE", length: 3, clue: "Frozen water" },
            { id: "sci_027", word: "OIL", length: 3, clue: "Viscous liquid derived from petroleum" },
            { id: "sci_028", word: "LAB", length: 3, clue: "Short for laboratory" },
            { id: "sci_029", word: "ZINC", length: 4, clue: "Chemical element with symbol Zn" },
            { id: "sci_030", word: "GOLD", length: 4, clue: "Precious yellow metal element" },
            { id: "sci_031", word: "NEON", length: 4, clue: "Noble gas used in lights" },
            { id: "sci_032", word: "VOLT", length: 4, clue: "Unit of electric potential" },
            { id: "sci_033", word: "WATT", length: 4, clue: "Unit of power" },
            { id: "sci_034", word: "NODE", length: 4, clue: "Point at which lines or pathways intersect" },
            { id: "sci_035", word: "VEIN", length: 4, clue: "Tube carrying blood to the heart" },
            { id: "sci_036", word: "SKIN", length: 4, clue: "Outer covering of the body" },
            { id: "sci_037", word: "RAIN", length: 4, clue: "Liquid precipitation" },
            { id: "sci_038", word: "WIND", length: 4, clue: "Movement of air" },
            { id: "sci_039", word: "CORE", length: 4, clue: "Central part of the earth" },
            { id: "sci_040", word: "DUST", length: 4, clue: "Fine powder of earth or waste" },
            { id: "sci_041", word: "STEM", length: 4, clue: "Main body or stalk of a plant" },
            { id: "sci_042", word: "TREE", length: 4, clue: "Woody perennial plant" },
            { id: "sci_043", word: "BIRD", length: 4, clue: "Warm-blooded egg-laying vertebrate" },
            { id: "sci_044", word: "FISH", length: 4, clue: "Limbless cold-blooded vertebrate with gills" },
            { id: "sci_045", word: "FOG", length: 3, clue: "Thick cloud of water droplets" },
            { id: "sci_046", word: "SUN", length: 3, clue: "Star around which the earth orbits" },
            { id: "sci_047", word: "SKY", length: 3, clue: "Region of the atmosphere seen from earth" },
            { id: "sci_048", word: "AIR", length: 3, clue: "Invisible gaseous substance surrounding earth" },
            { id: "sci_049", word: "ORE", length: 3, clue: "Naturally occurring solid material" },
            { id: "sci_050", word: "ASH", length: 3, clue: "Powdery residue left after burning" }
        ]
    },
    math_builder: {
        difficulty_level: 2,
        description: "Equations, operations & patterns.",
        color: "teal",
        words: [
            { id: "mth_001", word: "RATIO", length: 5, clue: "The quantitative relation between two amounts" },
            { id: "mth_002", word: "SUM", length: 3, clue: "The result of adding two or more numbers" },
            { id: "mth_003", word: "ACUTE", length: 5, clue: "An angle measuring less than 90 degrees" },
            { id: "mth_004", word: "PRIME", length: 5, clue: "Number divisible only by one and itself" },
            { id: "mth_005", word: "GRAPH", length: 5, clue: "A diagram showing the relation between variable quantities" },
            { id: "mth_006", word: "AXIS", length: 4, clue: "A fixed reference line for the measurement of coordinates" },
            { id: "mth_007", word: "MEAN", length: 4, clue: "The average of a set of numbers" },
            { id: "mth_008", word: "AREA", length: 4, clue: "The extent or measurement of a surface" },
            { id: "mth_009", "word": "CUBE", length: 4, clue: "A number multiplied by itself three times" },
            { id: "mth_010", word: "EQUAL", length: 5, clue: "Being the same in quantity, size, or value" },
            { id: "mth_011", word: "PLUS", length: 4, clue: "Symbol indicating addition" },
            { id: "mth_012", word: "UNIT", length: 4, clue: "Standard quantity for measurement" },
            { id: "mth_013", word: "ZERO", length: 4, clue: "No quantity or number" },
            { id: "mth_014", word: "MODE", length: 4, clue: "Most frequent number in a dataset" },
            { id: "mth_015", word: "ROOT", length: 4, clue: "Number that produces a given number when squared" },
            { id: "mth_016", word: "CONE", length: 4, clue: "Solid or hollow object with a circular base and a point" },
            { id: "mth_017", word: "LINE", length: 4, clue: "Long, narrow mark or band" },
            { id: "mth_018", word: "OVAL", length: 4, clue: "Having a rounded and slightly elongated outline" },
            { id: "mth_019", word: "DATA", length: 4, clue: "Facts and statistics collected for reference" },
            { id: "mth_020", word: "LESS", length: 4, clue: "Smaller amount of" },
            { id: "mth_021", word: "EVEN", length: 4, clue: "Divisible by two without a remainder" },
            { id: "mth_022", word: "MATH", length: 4, clue: "Study of numbers, shapes, and patterns" },
            { id: "mth_023", word: "ODD", length: 3, clue: "Not divisible by two" },
            { id: "mth_024", word: "ARC", length: 3, clue: "Part of the circumference of a circle" },
            { id: "mth_025", word: "PIE", length: 3, clue: "Type of chart" },
            { id: "mth_026", word: "ADD", length: 3, clue: "Join something to something else" },
            { id: "mth_027", word: "SET", length: 3, clue: "Collection of distinct objects" },
            { id: "mth_028", word: "NET", length: 3, clue: "2D pattern that folds into a 3D shape" },
            { id: "mth_029", word: "RAY", length: 3, clue: "Line with a start point but no end point" },
            { id: "mth_030", word: "TEN", length: 3, clue: "Base of our number system" },
            { id: "mth_031", word: "ALGEBRA", length: 7, clue: "Branch of mathematics using symbols" },
            { id: "mth_032", word: "RANGE", length: 5, clue: "Difference between largest and smallest values" },
            { id: "mth_033", word: "SCOPE", length: 5, clue: "Extent of the area or subject matter" },
            { id: "mth_034", word: "DIGIT", length: 5, clue: "Any number from 0 to 9" },
            { id: "mth_035", word: "INDEX", length: 5, clue: "Power or exponent" },
            { id: "mth_036", word: "LOGIC", length: 5, clue: "Reasoning conducted according to strict principles" },
            { id: "mth_037", word: "SLOPE", length: 5, clue: "Gradient of a line" },
            { id: "mth_038", word: "PLANE", length: 5, clue: "Flat surface with no thickness" },
            { id: "mth_039", word: "ANGLE", length: 5, clue: "Space between two intersecting lines" },
            { id: "mth_040", word: "POINT", length: 5, clue: "Exact location in space" },
            { id: "mth_041", word: "VALUE", length: 5, clue: "Numerical amount denoted by a symbol" },
            { id: "mth_042", word: "LIMIT", length: 5, clue: "Value that a function approaches" },
            { id: "mth_043", word: "DELTA", length: 5, clue: "Difference between two values" },
            { id: "mth_044", word: "WIDTH", length: 5, clue: "Measurement from side to side" },
            { id: "mth_045", word: "DEPTH", length: 5, clue: "Distance from top to bottom" },
            { id: "mth_046", word: "COUNT", length: 5, clue: "Determine the total number of" },
            { id: "mth_047", word: "TOTAL", length: 5, clue: "Complete amount" },
            { id: "mth_048", word: "FRACTION", length: 8, clue: "Numerical quantity that is not a whole number" },
            { id: "mth_049", word: "DECIMAL", length: 7, clue: "Relating to or denoting a system of numbers and arithmetic based on the number ten" },
            { id: "mth_050", word: "PERCENT", length: 7, clue: "One part in every hundred" }
        ]
    },
    english_master: {
        difficulty_level: 3,
        description: "Grammar, reading skills & vocab.",
        color: "pink",
        words: [
            { id: "eng_001", word: "IRONY", length: 5, clue: "Contrast between expectation and reality" },
            { id: "eng_002", word: "VERB", length: 4, clue: "A word used to describe an action or state" },
            { id: "eng_003", word: "HAIKU", length: 5, clue: "Japanese poem of seventeen syllables" },
            { id: "eng_004", word: "THEME", length: 5, clue: "The central topic or message within a narrative" },
            { id: "eng_005", word: "NOUN", length: 4, clue: "A word identifying a person, place, or thing" },
            { id: "eng_006", word: "SIMILE", length: 6, clue: "Comparison of two things using 'like' or 'as'" },
            { id: "eng_007", word: "STANZA", length: 6, clue: "A group of lines forming the basic unit in a poem" },
            { id: "eng_008", word: "PLOT", length: 4, clue: "The main events of a play or novel" },
            { id: "eng_009", word: "GENRE", length: 5, clue: "A category of artistic composition" },
            { id: "eng_010", word: "SYNTAX", length: 6, clue: "The arrangement of words and phrases" },
            { id: "eng_011", word: "POEM", length: 4, clue: "Piece of writing with rhythm" },
            { id: "eng_012", word: "RHYME", length: 5, clue: "Correspondence of sound between words" },
            { id: "eng_013", word: "TONE", length: 4, clue: "The general character or attitude of a place or piece" },
            { id: "eng_014", word: "EPIC", length: 4, clue: "Long poem narrating deeds of a hero" },
            { id: "eng_015", word: "MYTH", length: 4, clue: "Traditional story explaining early history" },
            { id: "eng_016", word: "ODE", length: 3, clue: "Lyric poem addressing a particular subject" },
            { id: "eng_017", word: "PEN", length: 3, clue: "Instrument for writing" },
            { id: "eng_018", word: "PUN", length: 3, clue: "Joke exploiting different meanings of a word" },
            { id: "eng_019", word: "ACT", length: 3, clue: "Main division of a play" },
            { id: "eng_020", word: "ART", length: 3, clue: "Expression of human creative skill" },
            { id: "eng_021", word: "TEXT", length: 4, clue: "Written or printed work" },
            { id: "eng_022", word: "READ", length: 4, clue: "Look at and comprehend" },
            { id: "eng_023", word: "BOOK", length: 4, clue: "Written or printed work fastened together" },
            { id: "eng_024", word: "PAGE", length: 4, clue: "One side of a sheet of paper" },
            { id: "eng_025", word: "WORD", length: 4, clue: "Single distinct meaningful element of speech" },
            { id: "eng_026", word: "NOTE", length: 4, clue: "Brief record of something" },
            { id: "eng_027", word: "DRAMA", length: 5, clue: "Play for theater, radio, or television" },
            { id: "eng_028", word: "IMAGE", length: 5, clue: "Representation of the external form of a person or thing" },
            { id: "eng_029", word: "STYLE", length: 5, clue: "Manner of doing something" },
            { id: "eng_030", word: "VOICE", length: 5, clue: "Sound produced in a person's larynx" },
            { id: "eng_031", word: "TENSE", length: 5, clue: "Set of forms indicating value of time" },
            { id: "eng_032", word: "PROSE", length: 5, clue: "Written or spoken language in ordinary form" },
            { id: "eng_033", word: "ESSAY", length: 5, clue: "Short piece of writing on a particular subject" },
            { id: "eng_034", word: "NOVEL", length: 5, clue: "Fictitious prose narrative" },
            { id: "eng_035", word: "STORY", length: 5, clue: "Account of imaginary or real people" },
            { id: "eng_036", word: "COMMA", length: 5, clue: "Punctuation mark indicating a pause" },
            { id: "eng_037", word: "COLON", length: 5, clue: "Punctuation mark used to precede a list" },
            { id: "eng_038", word: "POINT", length: 5, clue: "Full stop" },
            { id: "eng_039", word: "TITLE", length: 5, clue: "Name of a book" },
            { id: "eng_040", word: "AUTHOR", length: 6, clue: "Writer of a book" },
            { id: "eng_041", word: "POETRY", length: 6, clue: "Literary work in which special intensity is given" },
            { id: "eng_042", word: "SONNET", length: 6, clue: "Poem of fourteen lines" },
            { id: "eng_043", word: "SATIRE", length: 6, clue: "Use of humor to criticize people's stupidity" },
            { id: "eng_044", word: "RHYTHM", length: 6, clue: "Strong, regular, repeated pattern of sound" },
            { id: "eng_045", word: "SYMBOL", length: 6, clue: "Mark or character used as a conventional representation" },
            { id: "eng_046", word: "EDIT", length: 4, clue: "Prepare for publication" },
            { id: "eng_047", word: "DRAFT", length: 5, clue: "Preliminary version of a piece of writing" },
            { id: "eng_048", word: "WRITE", length: 5, clue: "Mark letters on a surface" },
            { id: "eng_049", word: "LYRIC", length: 5, clue: "Expressing the writer's emotions" },
            { id: "eng_050", word: "VERSE", length: 5, clue: "Writing arranged with a metrical rhythm" }
        ]
    },
    history_quest: {
        difficulty_level: 2,
        description: "Empires, leaders & key events.",
        color: "purple",
        words: [
            { id: "his_001", word: "AZTEC", length: 5, clue: "Indigenous empire in central Mexico before Spanish conquest" },
            { id: "his_002", word: "NILE", length: 4, clue: "River essential to ancient Egyptian civilization" },
            { id: "his_003", word: "ALLY", length: 4, clue: "A state formally cooperating with another for military purpose" },
            { id: "his_004", word: "ROME", length: 4, clue: "Capital of an ancient republic and empire in Italy" },
            { id: "his_005", word: "MAYA", length: 4, clue: "Mesoamerican civilization known for its hieroglyphic script" },
            { id: "his_006", word: "KING", length: 4, clue: "Male ruler of an independent state" },
            { id: "his_007", word: "WAR", length: 3, clue: "A state of armed conflict between different nations" },
            { id: "his_008", "word": "INCA", length: 4, clue: "Largest empire in pre-Columbian America" },
            { id: "his_009", "word": "TOMB", length: 4, clue: "A large vault for burying the dead" },
            { id: "his_010", "word": "ERA", length: 3, clue: "A long and distinct period of history" },
            { id: "his_011", word: "GOLD", length: 4, clue: "Yellow precious metal" },
            { id: "his_012", word: "LAND", length: 4, clue: "Part of earth's surface not covered by water" },
            { id: "his_013", word: "HERO", length: 4, clue: "Person admired for courage or achievements" },
            { id: "his_014", word: "FLAG", length: 4, clue: "Piece of cloth serving as a country's symbol" },
            { id: "his_015", word: "FORT", length: 4, clue: "Strong building for military defense" },
            { id: "his_016", word: "ARMY", length: 4, clue: "Organized military force" },
            { id: "his_017", word: "NAVY", length: 4, clue: "Branch of armed services that conducts military operations at sea" },
            { id: "his_018", word: "LAW", length: 3, clue: "System of rules which a country or community recognizes" },
            { id: "his_019", word: "TAX", length: 3, clue: "Compulsory contribution to state revenue" },
            { id: "his_020", word: "BOW", length: 3, clue: "Weapon for shooting arrows" },
            { id: "his_021", word: "AGE", length: 3, clue: "Length of time that a person has lived" },
            { id: "his_022", word: "MAP", length: 3, clue: "Diagrammatic representation of an area" },
            { id: "his_023", word: "OIL", length: 3, clue: "Resource causing many modern conflicts" },
            { id: "his_024", word: "AID", length: 3, clue: "Help, typically of a practical nature" },
            { id: "his_025", word: "GUN", length: 3, clue: "Weapon incorporating a metal tube" },
            { id: "his_026", word: "PEACE", length: 5, clue: "Freedom from disturbance" },
            { id: "his_027", word: "QUEEN", length: 5, clue: "Female ruler of an independent state" },
            { id: "his_028", word: "POWER", length: 5, clue: "Ability to do something" },
            { id: "his_029", word: "CROWN", length: 5, clue: "Circular ornamental headdress worn by a monarch" },
            { id: "his_030", word: "COURT", length: 5, clue: "Tribunal presided over by a judge" },
            { id: "his_031", word: "TRADE", length: 5, clue: "Action of buying and selling goods" },
            { id: "his_032", word: "EVENT", length: 5, clue: "Thing that happens" },
            { id: "his_033", word: "UNION", length: 5, clue: "Action or fact of joining or being joined" },
            { id: "his_034", word: "REBEL", length: 5, clue: "Person who rises in opposition" },
            { id: "his_035", word: "LEGAL", length: 5, clue: "Of or appointed by law" },
            { id: "his_036", word: "CIVIL", length: 5, clue: "Relating to ordinary citizens" },
            { id: "his_037", word: "CHINA", length: 5, clue: "Ancient Asian civilization" },
            { id: "his_038", word: "EGYPT", length: 5, clue: "Country linking northeast Africa with the Middle East" },
            { id: "his_039", word: "GREEK", length: 5, clue: "Native or inhabitant of Greece" },
            { id: "his_040", word: "TITLE", length: 5, clue: "Name that describes someone's position" },
            { id: "his_041", word: "EMPIRE", length: 6, clue: "Extensive group of states or countries under a single supreme authority" },
            { id: "his_042", word: "COLONY", length: 6, clue: "Country or area under the full or partial political control of another" },
            { id: "his_043", word: "LEADER", length: 6, clue: "Person who leads or commands a group" },
            { id: "his_044", word: "TREATY", length: 6, clue: "Formally concluded and ratified agreement" },
            { id: "his_045", word: "NATION", length: 6, clue: "Large body of people united by common descent" },
            { id: "his_046", word: "BATTLE", length: 6, clue: "Sustained fight between large organized armed forces" },
            { id: "his_047", word: "RIGHTS", length: 6, clue: "Moral or legal entitlement" },
            { id: "his_048", word: "VOTE", length: 4, clue: "Formal indication of a choice" },
            { id: "his_049", word: "PACT", length: 4, clue: "Formal agreement between individuals or parties" },
            { id: "his_050", word: "LORD", length: 4, clue: "Someone or something having power" }
        ]
    }
};
